"""Excel TemplateParser — Phase B2.

Reads the 4-sheet workbook produced by build_fixture.py and returns a
normalised dict ready for the import service (B3).

Sheet layout (canonical — defined in build_fixture.py):
  metadata         — key/value pairs (report_month, version_type, source_type, …)
  delivery_counts  — phase, count
  n12m             — section, line_item, display_name, is_calculated, sort_order, <month…>
  phase_comparison — line_item, p1, p2, p3, p4, p5, total
"""

from datetime import datetime as _datetime
from decimal import Decimal
from pathlib import Path

import openpyxl

from app.domain.enums import Phase, SectionType, SeriesType, PHASES


def _cell_to_date_str(value) -> str:
    """Convert an openpyxl cell value to a YYYY-MM-DD string.

    openpyxl returns datetime objects when a cell is formatted as a date in
    Excel (even if the underlying value looks like a string). Normalise both
    cases to "YYYY-MM-DD".
    """
    if isinstance(value, _datetime):
        return value.strftime("%Y-%m-%d")
    return str(value)


class TemplateParser:
    def __init__(self, path: Path | str) -> None:
        self._path = Path(path)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def parse(self) -> dict:
        wb = openpyxl.load_workbook(self._path, data_only=True)
        return {
            "import_meta": self._parse_metadata(wb["metadata"]),
            "delivery_counts": self._parse_delivery_counts(wb["delivery_counts"]),
            "n12m_line_items": self._parse_n12m(wb["n12m"]),
            "phase_comparison_rows": self._parse_phase_comparison(wb["phase_comparison"]),
        }

    @staticmethod
    def _parse_series_type(value: str) -> SeriesType:
        return TemplateParser.parse_series_type(value)

    @staticmethod
    def parse_series_type(value: str) -> SeriesType:
        """Validate and convert a string to SeriesType enum.

        This guard is the canonical converter for series_type strings throughout
        the import pipeline. The xlsx fixture does not contain series_type data
        (ncf_series is generated by the cascade service in B4), but this method
        is called by the cascade service to ensure enum hygiene — preventing the
        raw-string drift bug that burned v1.

        Raises ValueError for any unrecognised or incorrectly-cased value.
        Case-sensitive by design — 'Periodic' is not 'periodic'.
        """
        if value is None:
            raise TypeError("parse_series_type requires a string, got None")
        try:
            # SeriesType is a str enum — direct lookup by value (case-sensitive)
            return SeriesType(value)
        except ValueError:
            raise ValueError(
                f"Invalid series_type {value!r}. "
                f"Must be one of: {[e.value for e in SeriesType]}"
            )

    # ------------------------------------------------------------------
    # Sheet parsers
    # ------------------------------------------------------------------

    def _parse_metadata(self, ws) -> dict:
        rows = list(ws.iter_rows(min_row=2, values_only=True))
        # Use _cell_to_date_str so date-formatted cells (e.g. report_month) don't
        # produce "2025-09-01 00:00:00" via plain str().
        meta = {str(k): _cell_to_date_str(v) for k, v in rows if k is not None}
        # Ensure 'name' key is always present — use filename stem as fallback
        meta.setdefault("name", self._path.stem)
        return meta

    def _parse_delivery_counts(self, ws) -> list[dict]:
        rows = list(ws.iter_rows(min_row=2, values_only=True))
        result = []
        for phase_str, count in rows:
            if phase_str is None:
                continue
            phase = Phase(str(phase_str))
            result.append({"phase": phase, "count": int(count)})
        return result

    def _parse_n12m(self, ws) -> list[dict]:
        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            return []

        header = rows[0]
        # Month columns start after the fixed columns:
        # section, line_item, display_name, is_calculated, sort_order
        FIXED = 5
        # Use _cell_to_date_str — Excel may auto-convert date-string headers to
        # datetime objects, which str() would render as "2025-10-01 00:00:00".
        month_headers = [_cell_to_date_str(h) for h in header[FIXED:] if h is not None]

        result = []
        for data_row in rows[1:]:
            if data_row[0] is None:
                continue
            section_str, line_item, display_name, is_calculated, sort_order = data_row[:FIXED]

            # Enforce SectionType enum — no string literals
            section = SectionType(str(section_str))

            entries = []
            for i, month in enumerate(month_headers):
                raw = data_row[FIXED + i]
                # Convert via str() to avoid float precision issues
                value = Decimal(str(raw if raw is not None else 0))
                entries.append({"month": month, "value": value})

            result.append({
                "section": section,
                "line_item": str(line_item),
                "display_name": str(display_name) if display_name is not None else str(line_item),
                "is_calculated": bool(is_calculated),
                "sort_order": int(sort_order) if sort_order is not None else 0,
                "entries": entries,
            })

        return result

    def _parse_phase_comparison(self, ws) -> list[dict]:
        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            return []

        # Header: line_item, p1, p2, p3, p4, p5, total
        header = rows[0]
        # Phase columns — everything after line_item
        phase_columns = [str(h) for h in header[1:] if h is not None]

        result = []
        for data_row in rows[1:]:
            if data_row[0] is None:
                continue
            line_item = str(data_row[0])
            for i, phase_str in enumerate(phase_columns):
                phase = Phase(phase_str)
                raw = data_row[1 + i]
                current = Decimal(str(raw if raw is not None else 0))
                result.append({
                    "line_item": line_item,
                    "phase": phase,
                    "current": current,
                    "budget": None,
                    "delta": None,
                    "delta_pct": None,
                })

        return result
